//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickServiceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRequest
    {
        public long RequestId { get; set; }
        public string CustomerId { get; set; }
        public string ProblemStatement { get; set; }
        public string OrderId { get; set; }
        public string AssigneeId { get; set; }
        public string RequestStatus { get; set; }
        public Nullable<System.DateTime> TimeRequestRaised { get; set; }
        public Nullable<System.DateTime> TimeRequestAssigned { get; set; }
        public Nullable<System.DateTime> TimeRequestClosed { get; set; }
        public byte[] ImageUploaded { get; set; }
    
        public virtual CustomerDetail CustomerDetail { get; set; }
        public virtual StaffDetail StaffDetail { get; set; }
    }
}
