//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickServiceDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffDetail()
        {
            this.CustomerRequests = new HashSet<CustomerRequest>();
        }
    
        public string StaffId { get; set; }
        public string StaffName { get; set; }
        public string StaffPassword { get; set; }
        public Nullable<long> JobAssigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequest> CustomerRequests { get; set; }
    }
}
